import { Component } from '@angular/core';

@Component({
  selector: 'app-playlist-content',
  templateUrl: './playlist-content.component.html',
  styleUrls: ['./playlist-content.component.scss']
})
export class PlaylistContentComponent {
  playlistDetails = {
    href: "https://api.spotify.com/v1/playlists/3HwjSYpC3W9JT9i5GsonDJ/tracks?offset=0&limit=100",
    items: [
      {
        added_at: "2019-04-10T10:36:38Z",
        added_by: {
          external_urls: {
            spotify: "https://open.spotify.com/user/gon_nofx"
          },
          href: "https://api.spotify.com/v1/users/gon_nofx",
          id: "gon_nofx",
          type: "user",
          uri: "spotify:user:gon_nofx"
        },
        is_local: false,
        primary_color: null,
        track: {
          album: {
            album_type: "album",
            artists: [
              {
                external_urls: {
                  spotify: "https://open.spotify.com/artist/6i0KVTOvm96T55mbp742ks"
                },
                href: "https://api.spotify.com/v1/artists/6i0KVTOvm96T55mbp742ks",
                id: "6i0KVTOvm96T55mbp742ks",
                name: "Pennywise",
                type: "artist",
                uri: "spotify:artist:6i0KVTOvm96T55mbp742ks"
              }
            ],
            available_markets: [
              "AD",
              "AE",
              "AL",
              "AR",
              "AT",
              "AU",
              "BA",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "BY",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HR",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "KZ",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MK",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "SA",
              "SE",
              "SG",
              "SI",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "UA",
              "US",
              "UY",
              "VN",
              "XK",
              "ZA"
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/6oEh869vJQY1QdfZlVQ0ly"
            },
            href: "https://api.spotify.com/v1/albums/6oEh869vJQY1QdfZlVQ0ly",
            id: "6oEh869vJQY1QdfZlVQ0ly",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b2734a8168a723a90d7e187e3a5f",
                width: 640
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e024a8168a723a90d7e187e3a5f",
                width: 300
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d000048514a8168a723a90d7e187e3a5f",
                width: 64
              }
            ],
            name: "Land Of The Free?",
            release_date: "2001-06-19",
            release_date_precision: "day",
            total_tracks: 14,
            type: "album",
            uri: "spotify:album:6oEh869vJQY1QdfZlVQ0ly"
          },
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/6i0KVTOvm96T55mbp742ks"
              },
              href: "https://api.spotify.com/v1/artists/6i0KVTOvm96T55mbp742ks",
              id: "6i0KVTOvm96T55mbp742ks",
              name: "Pennywise",
              type: "artist",
              uri: "spotify:artist:6i0KVTOvm96T55mbp742ks"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AL",
            "AR",
            "AT",
            "AU",
            "BA",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "BY",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HR",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "KZ",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MK",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "SA",
            "SE",
            "SG",
            "SI",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "UA",
            "US",
            "UY",
            "VN",
            "XK",
            "ZA"
          ],
          disc_number: 1,
          duration_ms: 196120,
          episode: false,
          explicit: true,
          external_ids: {
            isrc: "USEP40338304"
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/3Id64dLhfH7z0mmcylxuNp"
          },
          href: "https://api.spotify.com/v1/tracks/3Id64dLhfH7z0mmcylxuNp",
          id: "3Id64dLhfH7z0mmcylxuNp",
          is_local: false,
          name: "Fuck Authority",
          popularity: 63,
          preview_url: "https://p.scdn.co/mp3-preview/1fe17feb9e22f7dc1b04028e73b3cff04c06fa12?cid=d4c71c36095842fc90271017bd8e5443",
          track: true,
          track_number: 4,
          type: "track",
          uri: "spotify:track:3Id64dLhfH7z0mmcylxuNp"
        },
        video_thumbnail: {
          url: null
        }
      },
      {
        added_at: "2019-03-28T19:23:16Z",
        added_by: {
          external_urls: {
            spotify: "https://open.spotify.com/user/gon_nofx"
          },
          href: "https://api.spotify.com/v1/users/gon_nofx",
          id: "gon_nofx",
          type: "user",
          uri: "spotify:user:gon_nofx"
        },
        is_local: false,
        primary_color: null,
        track: {
          album: {
            album_type: "album",
            artists: [
              {
                external_urls: {
                  spotify: "https://open.spotify.com/artist/4S2yOnmsWW97dT87yVoaSZ"
                },
                href: "https://api.spotify.com/v1/artists/4S2yOnmsWW97dT87yVoaSZ",
                id: "4S2yOnmsWW97dT87yVoaSZ",
                name: "NOFX",
                type: "artist",
                uri: "spotify:artist:4S2yOnmsWW97dT87yVoaSZ"
              }
            ],
            available_markets: [
              "AD",
              "AE",
              "AL",
              "AR",
              "AT",
              "AU",
              "BA",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "BY",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HR",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "KZ",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MK",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "SA",
              "SE",
              "SG",
              "SI",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "UA",
              "US",
              "UY",
              "VN",
              "XK",
              "ZA"
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/37hvw6OVfRLktCmFcU9zHE"
            },
            href: "https://api.spotify.com/v1/albums/37hvw6OVfRLktCmFcU9zHE",
            id: "37hvw6OVfRLktCmFcU9zHE",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b273530db954283883866bc21a95",
                width: 640
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e02530db954283883866bc21a95",
                width: 300
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d00004851530db954283883866bc21a95",
                width: 64
              }
            ],
            name: "Pump Up The Valuum",
            release_date: "2000-06-13",
            release_date_precision: "day",
            total_tracks: 14,
            type: "album",
            uri: "spotify:album:37hvw6OVfRLktCmFcU9zHE"
          },
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/4S2yOnmsWW97dT87yVoaSZ"
              },
              href: "https://api.spotify.com/v1/artists/4S2yOnmsWW97dT87yVoaSZ",
              id: "4S2yOnmsWW97dT87yVoaSZ",
              name: "NOFX",
              type: "artist",
              uri: "spotify:artist:4S2yOnmsWW97dT87yVoaSZ"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AL",
            "AR",
            "AT",
            "AU",
            "BA",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "BY",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HR",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "KZ",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MK",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "SA",
            "SE",
            "SG",
            "SI",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "UA",
            "US",
            "UY",
            "VN",
            "XK",
            "ZA"
          ],
          disc_number: 1,
          duration_ms: 178573,
          episode: false,
          explicit: false,
          external_ids: {
            isrc: "USEP40360104"
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/4kRDPODRnN9Cbyrcg9qTkE"
          },
          href: "https://api.spotify.com/v1/tracks/4kRDPODRnN9Cbyrcg9qTkE",
          id: "4kRDPODRnN9Cbyrcg9qTkE",
          is_local: false,
          name: "Dinosaurs Will Die",
          popularity: 51,
          preview_url: "https://p.scdn.co/mp3-preview/76b4672bcab7910fe67d17ac067b7600c5034076?cid=d4c71c36095842fc90271017bd8e5443",
          track: true,
          track_number: 4,
          type: "track",
          uri: "spotify:track:4kRDPODRnN9Cbyrcg9qTkE"
        },
        video_thumbnail: {
          url: null
        }
      },
      {
        added_at: "2019-03-28T19:26:02Z",
        added_by: {
          external_urls: {
            spotify: "https://open.spotify.com/user/gon_nofx"
          },
          href: "https://api.spotify.com/v1/users/gon_nofx",
          id: "gon_nofx",
          type: "user",
          uri: "spotify:user:gon_nofx"
        },
        is_local: false,
        primary_color: null,
        track: {
          album: {
            album_type: "album",
            artists: [
              {
                external_urls: {
                  spotify: "https://open.spotify.com/artist/4S2yOnmsWW97dT87yVoaSZ"
                },
                href: "https://api.spotify.com/v1/artists/4S2yOnmsWW97dT87yVoaSZ",
                id: "4S2yOnmsWW97dT87yVoaSZ",
                name: "NOFX",
                type: "artist",
                uri: "spotify:artist:4S2yOnmsWW97dT87yVoaSZ"
              }
            ],
            available_markets: [
              "AD",
              "AE",
              "AL",
              "AR",
              "AT",
              "AU",
              "BA",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "BY",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HR",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "KZ",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MK",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "SA",
              "SE",
              "SG",
              "SI",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "UA",
              "US",
              "UY",
              "VN",
              "XK",
              "ZA"
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/5dbWoqjHDExyrEJD9ftnay"
            },
            href: "https://api.spotify.com/v1/albums/5dbWoqjHDExyrEJD9ftnay",
            id: "5dbWoqjHDExyrEJD9ftnay",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b273f5f40f1013cd62539fac2e18",
                width: 640
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e02f5f40f1013cd62539fac2e18",
                width: 300
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d00004851f5f40f1013cd62539fac2e18",
                width: 64
              }
            ],
            name: "White Trash ......",
            release_date: "1992-12-30",
            release_date_precision: "day",
            total_tracks: 13,
            type: "album",
            uri: "spotify:album:5dbWoqjHDExyrEJD9ftnay"
          },
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/4S2yOnmsWW97dT87yVoaSZ"
              },
              href: "https://api.spotify.com/v1/artists/4S2yOnmsWW97dT87yVoaSZ",
              id: "4S2yOnmsWW97dT87yVoaSZ",
              name: "NOFX",
              type: "artist",
              uri: "spotify:artist:4S2yOnmsWW97dT87yVoaSZ"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AL",
            "AR",
            "AT",
            "AU",
            "BA",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "BY",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HR",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "KZ",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MK",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "SA",
            "SE",
            "SG",
            "SI",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "UA",
            "US",
            "UY",
            "VN",
            "XK",
            "ZA"
          ],
          disc_number: 1,
          duration_ms: 122160,
          episode: false,
          explicit: false,
          external_ids: {
            isrc: "USEP40310103"
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/5XhMeCYrRhQjL4sUoOmUCE"
          },
          href: "https://api.spotify.com/v1/tracks/5XhMeCYrRhQjL4sUoOmUCE",
          id: "5XhMeCYrRhQjL4sUoOmUCE",
          is_local: false,
          name: "Bob",
          popularity: 53,
          preview_url: "https://p.scdn.co/mp3-preview/fdbeb7eeb9eb4c0a87717045f1e89aea340af656?cid=d4c71c36095842fc90271017bd8e5443",
          track: true,
          track_number: 3,
          type: "track",
          uri: "spotify:track:5XhMeCYrRhQjL4sUoOmUCE"
        },
        video_thumbnail: {
          url: null
        }
      },
      {
        added_at: "2020-11-02T15:29:06Z",
        added_by: {
          external_urls: {
            spotify: "https://open.spotify.com/user/gon_nofx"
          },
          href: "https://api.spotify.com/v1/users/gon_nofx",
          id: "gon_nofx",
          type: "user",
          uri: "spotify:user:gon_nofx"
        },
        is_local: false,
        primary_color: null,
        track: {
          album: {
            album_type: "album",
            artists: [
              {
                external_urls: {
                  spotify: "https://open.spotify.com/artist/4S2yOnmsWW97dT87yVoaSZ"
                },
                href: "https://api.spotify.com/v1/artists/4S2yOnmsWW97dT87yVoaSZ",
                id: "4S2yOnmsWW97dT87yVoaSZ",
                name: "NOFX",
                type: "artist",
                uri: "spotify:artist:4S2yOnmsWW97dT87yVoaSZ"
              }
            ],
            available_markets: [
              "AD",
              "AE",
              "AL",
              "AR",
              "AT",
              "AU",
              "BA",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "BY",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HR",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "KZ",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MK",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "SA",
              "SE",
              "SG",
              "SI",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "UA",
              "US",
              "UY",
              "VN",
              "XK",
              "ZA"
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/5QdsrZhTTJFAcIeiKSqIZt"
            },
            href: "https://api.spotify.com/v1/albums/5QdsrZhTTJFAcIeiKSqIZt",
            id: "5QdsrZhTTJFAcIeiKSqIZt",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b2736983bc9d98d9ae5d858fb46d",
                width: 640
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e026983bc9d98d9ae5d858fb46d",
                width: 300
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d000048516983bc9d98d9ae5d858fb46d",
                width: 64
              }
            ],
            name: "Ribbed - Live in a Dive",
            release_date: "2018-08-03",
            release_date_precision: "day",
            total_tracks: 14,
            type: "album",
            uri: "spotify:album:5QdsrZhTTJFAcIeiKSqIZt"
          },
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/4S2yOnmsWW97dT87yVoaSZ"
              },
              href: "https://api.spotify.com/v1/artists/4S2yOnmsWW97dT87yVoaSZ",
              id: "4S2yOnmsWW97dT87yVoaSZ",
              name: "NOFX",
              type: "artist",
              uri: "spotify:artist:4S2yOnmsWW97dT87yVoaSZ"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AL",
            "AR",
            "AT",
            "AU",
            "BA",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "BY",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HR",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "KZ",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MK",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "SA",
            "SE",
            "SG",
            "SI",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "UA",
            "US",
            "UY",
            "VN",
            "XK",
            "ZA"
          ],
          disc_number: 1,
          duration_ms: 161572,
          episode: false,
          explicit: false,
          external_ids: {
            isrc: "USFW41890201"
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/1Fe3yiTQWQCgAEGuz0YKpp"
          },
          href: "https://api.spotify.com/v1/tracks/1Fe3yiTQWQCgAEGuz0YKpp",
          id: "1Fe3yiTQWQCgAEGuz0YKpp",
          is_local: false,
          name: "Green Corn",
          popularity: 26,
          preview_url: "https://p.scdn.co/mp3-preview/22a1068eaba04b31e7c41ba6bfff475d1e1c2bef?cid=d4c71c36095842fc90271017bd8e5443",
          track: true,
          track_number: 1,
          type: "track",
          uri: "spotify:track:1Fe3yiTQWQCgAEGuz0YKpp"
        },
        video_thumbnail: {
          url: null
        }
      },
      {
        added_at: "2020-11-02T15:29:19Z",
        added_by: {
          external_urls: {
            spotify: "https://open.spotify.com/user/gon_nofx"
          },
          href: "https://api.spotify.com/v1/users/gon_nofx",
          id: "gon_nofx",
          type: "user",
          uri: "spotify:user:gon_nofx"
        },
        is_local: false,
        primary_color: null,
        track: {
          album: {
            album_type: "album",
            artists: [
              {
                external_urls: {
                  spotify: "https://open.spotify.com/artist/4S2yOnmsWW97dT87yVoaSZ"
                },
                href: "https://api.spotify.com/v1/artists/4S2yOnmsWW97dT87yVoaSZ",
                id: "4S2yOnmsWW97dT87yVoaSZ",
                name: "NOFX",
                type: "artist",
                uri: "spotify:artist:4S2yOnmsWW97dT87yVoaSZ"
              }
            ],
            available_markets: [
              "AD",
              "AE",
              "AL",
              "AR",
              "AT",
              "AU",
              "BA",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "BY",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HR",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "KZ",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MK",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "SA",
              "SE",
              "SG",
              "SI",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "UA",
              "US",
              "UY",
              "VN",
              "XK",
              "ZA"
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/5QdsrZhTTJFAcIeiKSqIZt"
            },
            href: "https://api.spotify.com/v1/albums/5QdsrZhTTJFAcIeiKSqIZt",
            id: "5QdsrZhTTJFAcIeiKSqIZt",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b2736983bc9d98d9ae5d858fb46d",
                width: 640
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e026983bc9d98d9ae5d858fb46d",
                width: 300
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d000048516983bc9d98d9ae5d858fb46d",
                width: 64
              }
            ],
            name: "Ribbed - Live in a Dive",
            release_date: "2018-08-03",
            release_date_precision: "day",
            total_tracks: 14,
            type: "album",
            uri: "spotify:album:5QdsrZhTTJFAcIeiKSqIZt"
          },
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/4S2yOnmsWW97dT87yVoaSZ"
              },
              href: "https://api.spotify.com/v1/artists/4S2yOnmsWW97dT87yVoaSZ",
              id: "4S2yOnmsWW97dT87yVoaSZ",
              name: "NOFX",
              type: "artist",
              uri: "spotify:artist:4S2yOnmsWW97dT87yVoaSZ"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AL",
            "AR",
            "AT",
            "AU",
            "BA",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "BY",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HR",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "KZ",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MK",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "SA",
            "SE",
            "SG",
            "SI",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "UA",
            "US",
            "UY",
            "VN",
            "XK",
            "ZA"
          ],
          disc_number: 1,
          duration_ms: 130009,
          episode: false,
          explicit: false,
          external_ids: {
            isrc: "USFW41890205"
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/1wkfQ57zlg5hs0CU9Bk12g"
          },
          href: "https://api.spotify.com/v1/tracks/1wkfQ57zlg5hs0CU9Bk12g",
          id: "1wkfQ57zlg5hs0CU9Bk12g",
          is_local: false,
          name: "Just the Flu",
          popularity: 25,
          preview_url: "https://p.scdn.co/mp3-preview/90eca2aafefbe0a4d687db07c6d9fa54bedfad66?cid=d4c71c36095842fc90271017bd8e5443",
          track: true,
          track_number: 5,
          type: "track",
          uri: "spotify:track:1wkfQ57zlg5hs0CU9Bk12g"
        },
        video_thumbnail: {
          url: null
        }
      },
      {
        added_at: "2020-11-02T15:29:24Z",
        added_by: {
          external_urls: {
            spotify: "https://open.spotify.com/user/gon_nofx"
          },
          href: "https://api.spotify.com/v1/users/gon_nofx",
          id: "gon_nofx",
          type: "user",
          uri: "spotify:user:gon_nofx"
        },
        is_local: false,
        primary_color: null,
        track: {
          album: {
            album_type: "album",
            artists: [
              {
                external_urls: {
                  spotify: "https://open.spotify.com/artist/4S2yOnmsWW97dT87yVoaSZ"
                },
                href: "https://api.spotify.com/v1/artists/4S2yOnmsWW97dT87yVoaSZ",
                id: "4S2yOnmsWW97dT87yVoaSZ",
                name: "NOFX",
                type: "artist",
                uri: "spotify:artist:4S2yOnmsWW97dT87yVoaSZ"
              }
            ],
            available_markets: [
              "AD",
              "AE",
              "AL",
              "AR",
              "AT",
              "AU",
              "BA",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "BY",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HR",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "KZ",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MK",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "SA",
              "SE",
              "SG",
              "SI",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "UA",
              "US",
              "UY",
              "VN",
              "XK",
              "ZA"
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/5QdsrZhTTJFAcIeiKSqIZt"
            },
            href: "https://api.spotify.com/v1/albums/5QdsrZhTTJFAcIeiKSqIZt",
            id: "5QdsrZhTTJFAcIeiKSqIZt",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b2736983bc9d98d9ae5d858fb46d",
                width: 640
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e026983bc9d98d9ae5d858fb46d",
                width: 300
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d000048516983bc9d98d9ae5d858fb46d",
                width: 64
              }
            ],
            name: "Ribbed - Live in a Dive",
            release_date: "2018-08-03",
            release_date_precision: "day",
            total_tracks: 14,
            type: "album",
            uri: "spotify:album:5QdsrZhTTJFAcIeiKSqIZt"
          },
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/4S2yOnmsWW97dT87yVoaSZ"
              },
              href: "https://api.spotify.com/v1/artists/4S2yOnmsWW97dT87yVoaSZ",
              id: "4S2yOnmsWW97dT87yVoaSZ",
              name: "NOFX",
              type: "artist",
              uri: "spotify:artist:4S2yOnmsWW97dT87yVoaSZ"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AL",
            "AR",
            "AT",
            "AU",
            "BA",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "BY",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HR",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "KZ",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MK",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "SA",
            "SE",
            "SG",
            "SI",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "UA",
            "US",
            "UY",
            "VN",
            "XK",
            "ZA"
          ],
          disc_number: 1,
          duration_ms: 130394,
          episode: false,
          explicit: false,
          external_ids: {
            isrc: "USFW41890206"
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/3HhXID32pdh6IQiraxMTd6"
          },
          href: "https://api.spotify.com/v1/tracks/3HhXID32pdh6IQiraxMTd6",
          id: "3HhXID32pdh6IQiraxMTd6",
          is_local: false,
          name: "El Lay",
          popularity: 23,
          preview_url: "https://p.scdn.co/mp3-preview/0eb6a0d30cdedc05bba0c0bf5059ccb5f5c1c91c?cid=d4c71c36095842fc90271017bd8e5443",
          track: true,
          track_number: 6,
          type: "track",
          uri: "spotify:track:3HhXID32pdh6IQiraxMTd6"
        },
        video_thumbnail: {
          url: null
        }
      },
      {
        added_at: "2020-11-02T15:30:14Z",
        added_by: {
          external_urls: {
            spotify: "https://open.spotify.com/user/gon_nofx"
          },
          href: "https://api.spotify.com/v1/users/gon_nofx",
          id: "gon_nofx",
          type: "user",
          uri: "spotify:user:gon_nofx"
        },
        is_local: false,
        primary_color: null,
        track: {
          album: {
            album_type: "album",
            artists: [
              {
                external_urls: {
                  spotify: "https://open.spotify.com/artist/6xTk3EK5T9UzudENVvu9YB"
                },
                href: "https://api.spotify.com/v1/artists/6xTk3EK5T9UzudENVvu9YB",
                id: "6xTk3EK5T9UzudENVvu9YB",
                name: "Rancid",
                type: "artist",
                uri: "spotify:artist:6xTk3EK5T9UzudENVvu9YB"
              }
            ],
            available_markets: [
              "AD",
              "AE",
              "AL",
              "AR",
              "AT",
              "AU",
              "BA",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "BY",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HR",
              "HU",
              "ID",
              "IE",
              "IL",
              "IN",
              "IS",
              "IT",
              "JO",
              "KW",
              "KZ",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MD",
              "ME",
              "MK",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "RS",
              "RU",
              "SA",
              "SE",
              "SG",
              "SI",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "UA",
              "US",
              "UY",
              "VN",
              "XK",
              "ZA"
            ],
            external_urls: {
              spotify: "https://open.spotify.com/album/5mLjbMgKEL9ybpmKSQDoP4"
            },
            href: "https://api.spotify.com/v1/albums/5mLjbMgKEL9ybpmKSQDoP4",
            id: "5mLjbMgKEL9ybpmKSQDoP4",
            images: [
              {
                height: 640,
                url: "https://i.scdn.co/image/ab67616d0000b273a941fcd69cab4c8dc87c8a66",
                width: 640
              },
              {
                height: 300,
                url: "https://i.scdn.co/image/ab67616d00001e02a941fcd69cab4c8dc87c8a66",
                width: 300
              },
              {
                height: 64,
                url: "https://i.scdn.co/image/ab67616d00004851a941fcd69cab4c8dc87c8a66",
                width: 64
              }
            ],
            name: "...Honor Is All We Know (Deluxe Edition)",
            release_date: "2014-10-27",
            release_date_precision: "day",
            total_tracks: 17,
            type: "album",
            uri: "spotify:album:5mLjbMgKEL9ybpmKSQDoP4"
          },
          artists: [
            {
              external_urls: {
                spotify: "https://open.spotify.com/artist/6xTk3EK5T9UzudENVvu9YB"
              },
              href: "https://api.spotify.com/v1/artists/6xTk3EK5T9UzudENVvu9YB",
              id: "6xTk3EK5T9UzudENVvu9YB",
              name: "Rancid",
              type: "artist",
              uri: "spotify:artist:6xTk3EK5T9UzudENVvu9YB"
            }
          ],
          available_markets: [
            "AD",
            "AE",
            "AL",
            "AR",
            "AT",
            "AU",
            "BA",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "BY",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HR",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "KW",
            "KZ",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MD",
            "ME",
            "MK",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "SA",
            "SE",
            "SG",
            "SI",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "UA",
            "US",
            "UY",
            "VN",
            "XK",
            "ZA"
          ],
          disc_number: 1,
          duration_ms: 132026,
          episode: false,
          explicit: false,
          external_ids: {
            isrc: "USEP41335001"
          },
          external_urls: {
            spotify: "https://open.spotify.com/track/6dWFLuPwTUWTkF42fXlBIt"
          },
          href: "https://api.spotify.com/v1/tracks/6dWFLuPwTUWTkF42fXlBIt",
          id: "6dWFLuPwTUWTkF42fXlBIt",
          is_local: false,
          name: "Back Where I Belong",
          popularity: 33,
          preview_url: "https://p.scdn.co/mp3-preview/605fed64d96e88190a418c56427f16596cb156ea?cid=d4c71c36095842fc90271017bd8e5443",
          track: true,
          track_number: 1,
          type: "track",
          uri: "spotify:track:6dWFLuPwTUWTkF42fXlBIt"
        },
        video_thumbnail: {
          url: null
        }
      }
    ],
    limit: 100,
    next: null,
    offset: 0,
    previous: null,
    total: 7
  }
}